image: node:6

variables:
  # hostname of the DOKKU deployment server
  DEPLOY_SRV: deploy.cs.camosun.bc.ca

before_script:
  # Install ssh-agent if not already installed, it is required by Docker.
  # (change apt-get to yum if you use a CentOS-based image)
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'

  # Run ssh-agent (inside the build environment)
  - eval $(ssh-agent -s)

  # Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
  - ssh-add <(echo "$SSH_PRIVATE_KEY")

  # For Docker builds disable host key checking. Be aware that by adding that
  # you are suspectible to man-in-the-middle attacks.
  # WARNING: Use this only with the Docker executor, if you use it with shell
  # you will overwrite your user's SSH config.
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  # In order to properly check the server's host key, assuming you created the
  # SSH_SERVER_HOSTKEYS variable previously, uncomment the following two lines
  # instead.
  # - mkdir -p ~/.ssh
  # - '[[ -f /.dockerenv ]] && echo "$SSH_SERVER_HOSTKEYS" > ~/.ssh/known_hosts'

stages:
  - deploy-app
  - deploy-db

deploy_app_to_dokku:
  stage: deploy-app
  tags:
    # use a deploy runner
    - deploy
  script:
    # push the app to the deploy server
    - git subtree push --prefix app dokku@${DEPLOY_SRV}:$CI_PROJECT_NAME master
  only:
    - master

deploy_db_to_dokku:
  stage: deploy-db
  tags:
    # use a deploy runner
    - deploy
  script:
  # Unlink Service - the conditional is if this is being run on first deploy
  - 'ssh dokku@$DEPLOY_SRV mongo:unlink ${CI_PROJECT_NAME}-DB $CI_PROJECT_NAME || true'
  # Destroy DB - the conditional is if on first run, the DB hasn't been created yet
  - 'ssh dokku@$DEPLOY_SRV -- --force mongo:destroy ${CI_PROJECT_NAME}-DB || true'
  # Create/Re-create DB
  - ssh dokku@$DEPLOY_SRV mongo:create ${CI_PROJECT_NAME}-DB
  # Import dump
  - ssh dokku@$DEPLOY_SRV mongo:import ${CI_PROJECT_NAME}-DB < ./mongo-seed/dump.gz
  # link DB container to app
  - ssh dokku@$DEPLOY_SRV mongo:link ${CI_PROJECT_NAME}-DB $CI_PROJECT_NAME
  only:
    # Ensures that this stage ONLY RUNS on Master branch!
    - master
