version: "3"
services:
  node:
    container_name: node
    build: ./node   # Tells Docker Compose where to find the Dockerfile to build the image
    image: atomic-films # Tells Docker Compose what to name the image
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development # "development will be changed to "production" once app is published or performance suffers.
    ports:
      - "3000:3000"
    links:  # Tells node container to link to mongo container (Lab 9 Task 1)
      - db
    volumes:
      - ./app:/home/node/app
    command: "nodemon -L"
  db:
    image: mongo:3.4.10  # Mongo image
    container_name: mongo
    environment:
      - MONGO_INITDB_DATABASE=atomic-films # Sets up database to be initialized with data
    volumes:
      - ./mongo-seed:/docker-entrypoint-initdb.d # Mounts a Mongo-seed subdirectory to docker-entrypoint-initdb.d directory in container.