# Dockerfile for ICS 211 Lab 5 Node.js Server

# This is the base image on which all changes will be layered on. Comes from Docker Hub and uses latest mirror/patch release from Node.js LTS 6.x line.

FROM node:6

LABEL maintainer="Tim Evoy <tievo17@gmail.com>"